import type { Metadata } from "next";
import "./globals.css";
import "./my_css.css";
import Footer from "@/components/Footer";
import { Outfit, Montserrat } from 'next/font/google'

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: ['400', '500', '700'],
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['400', '600', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: {
    default: "Banginic",
    template: "%s - Banginic",
  },
  description: "Generated by create next app",
   icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${montserrat.variable}`}>
      <body
        className={`relative min-h-screen bg-gradient-to-br  from-slate-900 via-purple-900 to-slate-900 text-white 
         `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
