import type { Metadata } from "next";
import "./globals.css";
import "./my_css.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    default: "Banginic",
    template: "%s - Banginic",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative min-h-screen bg-gradient-to-br  from-slate-900 via-purple-900 to-slate-900 text-white 
         `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
